services:
  - type: web
    name: flask-ocr-face
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: API_KEY
        value: XAenIDLIyaELTeasy001LLyoheIDueasyMwIkQAhFweNbLVBRjzwVbNqa001
      - key: LARAVEL_URL
        value: https://e3b5-125-164-14-202.ngrok-free.app